DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TYPE IF EXISTS alert_type;
DROP TYPE IF EXISTS act_type;

CREATE TYPE alert_type AS ENUM ('none', 'email', 'text', 'call');
CREATE TYPE act_type AS ENUM ('user', 'editor', 'admin');

CREATE TABLE IF NOT EXISTS post (
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(240) NOT NULL,
    post_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body TEXT NOT NULL DEFAULT '',
    activity VARCHAR(240) NULL DEFAULT NULL,
    party VARCHAR(240) NULL DEFAULT NULL,
    start_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    start_time VARCHAR(100) NOT NULL DEFAULT '7:00 pm'
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
    display_name VARCHAR(100) NULL DEFAULT NULL,
    first_name VARCHAR(100) NULL DEFAULT NULL,
    last_name VARCHAR(100) NULL DEFAULT NULL,
    phone VARCHAR(20) NULL DEFAULT NULL,
    email VARCHAR(100) NULL DEFAULT NULL,
    password VARCHAR(100) NULL DEFAULT NULL,
    fb_id VARCHAR(100) NULL DEFAULT NULL,
    g_id VARCHAR(100) NULL DEFAULT NULL,
    ig_id VARCHAR(100) NULL DEFAULT NULL,
    g_photo VARCHAR(1000) NULL DEFAULT NULL,
    fb_photo VARCHAR(1000) NULL DEFAULT NULL,
    ig_photo VARCHAR(1000) NULL DEFAULT NULL,
    alerts alert_type NOT NULL DEFAULT 'email',
    birthday TIMESTAMPTZ NULL DEFAULT NULL,
    alert_days INT NULL DEFAULT NULL,
    alert_hour TIMESTAMP NULL DEFAULT NULL,
    account act_type NOT NULL DEFAULT 'user',
    edit_req BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (email)
);
